INSERT INTO producto (nombre, precio_unitario, tipo) VALUES ('Botella de agua 500mL', 0.50, 'Normal');
INSERT INTO producto (nombre, precio_unitario, tipo) VALUES ('Peluche de oso Disney 16x12x10cm', 12, 'Normal');           
INSERT INTO producto (nombre, precio_unitario, tipo) VALUES ('Coche Hot Wheels', 4.95, 'Normal');
INSERT INTO producto (nombre, precio_unitario, tipo) VALUES ('Ambrosias Tirma Pack 37', 3.69, 'Normal');
INSERT INTO producto (nombre, precio_unitario, tipo) VALUES ('Platos de cerámica', 5.00, 'Normal');
INSERT INTO producto (nombre, precio_unitario, tipo) VALUES ('Vasos de cristal', 5.00, 'Normal');
INSERT INTO producto (nombre, precio_unitario, tipo) VALUES ('Lasagna de atun', 2.79, 'Congelados');
INSERT INTO producto (nombre, precio_unitario, tipo) VALUES ('Lapices Alpino', 1.67, 'Normal');
INSERT INTO producto (nombre, precio_unitario, tipo) VALUES ('Munchitos', 1.00, 'Normal');
INSERT INTO producto (nombre, precio_unitario, tipo) VALUES ('Lego Piratas del Caribe Juego PSP', 49.99, 'Normal');
INSERT INTO producto (nombre, precio_unitario, tipo) VALUES ('Shrek la pelicula DVD', 99.99, 'Normal');
INSERT INTO producto (nombre, precio_unitario, tipo) VALUES ('Disco duro Seagate BarraCuda 3.5" 1TB SATA3', 50, 'Normal');
INSERT INTO producto (nombre, precio_unitario, tipo) VALUES ('Puerta de abeto maciza', 109, 'Normal');
INSERT INTO producto (nombre, precio_unitario, tipo) VALUES ('Grinder de yerbas 4 compartimentos', 4.20, 'Normal');
INSERT INTO producto (nombre, precio_unitario, tipo) VALUES ('Nintendo Switch Lite', 199.99, 'Normal');
INSERT INTO producto (nombre, precio_unitario, tipo) VALUES ('Camiseta Oasis Talla L', 25.34, 'Normal');
INSERT INTO producto (nombre, precio_unitario, tipo) VALUES ('Queso Parmesano', 3.69, 'Frio');
INSERT INTO producto (nombre, precio_unitario, tipo) VALUES ('Yogur estilo griego con stracciatella 4x125g.', 2.05, 'Frio');
INSERT INTO producto (nombre, precio_unitario, tipo) VALUES ('Falafel tradicional con Tofu Biológico 250g.', 5.78, 'Frio');
INSERT INTO producto (nombre, precio_unitario, tipo) VALUES ('Paquete de cartas de Yu-Gi-Oh!', 7.99, 'Normal');
INSERT INTO producto (nombre, precio_unitario, tipo) VALUES ('Pokemon Rojo', 26.04, 'Normal');
INSERT INTO producto (nombre, precio_unitario, tipo) VALUES ('Boligrafos BIC', 1.25, 'Normal');
INSERT INTO producto (nombre, precio_unitario, tipo) VALUES ('Auriculares inalambricos', 75, 'Normal');
INSERT INTO producto (nombre, precio_unitario, tipo) VALUES ('Teclado Logitech G213 Prodigy Teclado Gaming', 50, 'Normal');
INSERT INTO producto (nombre, precio_unitario, tipo) VALUES ('Cubitos de hielo', 2.00, 'Congelados');
INSERT INTO producto (nombre, precio_unitario, tipo) VALUES ('Helados Magnum almendrado', 3.00, 'Congelados');
INSERT INTO producto (nombre, precio_unitario, tipo) VALUES ('Playstation 2', 150, 'Normal');
INSERT INTO producto (nombre, precio_unitario, tipo) VALUES ('Crash of the Titans PS2', 50, 'Normal');
INSERT INTO producto (nombre, precio_unitario, tipo) VALUES ('Televisor TCL 32 Smart TV Android S615 HD negro', 179, 'Normal');
INSERT INTO producto (nombre, precio_unitario, tipo) VALUES ('Super Smash Bros Melee', 69, 'Normal');
INSERT INTO producto (nombre, precio_unitario, tipo) VALUES ('Danacol', 5.60, 'Frio');
INSERT INTO producto (nombre, precio_unitario, tipo) VALUES ('Langostinos', 7.89, 'Congelados');
INSERT INTO producto (nombre, precio_unitario, tipo) VALUES ('Dancing with the Devil: The Art of Starting Over Demi Lovato CD', 16.99, 'Normal');
INSERT INTO producto (nombre, precio_unitario, tipo) VALUES ('Mortadelo y Filemon La Pelicula', 5.99, 'Normal');
INSERT INTO producto (nombre, precio_unitario, tipo) VALUES ('Bolsa de guisantes', 3,20, 'Congelados');
INSERT INTO producto (nombre, precio_unitario, tipo) VALUES ('Chips Ahoy', 2,74, 'Normal');
INSERT INTO producto (nombre, precio_unitario, tipo) VALUES ('Oreos', 2,15, 'Normal');
INSERT INTO producto (nombre, precio_unitario, tipo) VALUES ('Llave inglesa', 5.49, 'Normal');
INSERT INTO producto (nombre, precio_unitario, tipo) VALUES ('Tarta helada', 10.50, 'Congelados');
INSERT INTO producto (nombre, precio_unitario, tipo) VALUES ('Clipper de fresa 1,5 L', 1.00, 'Frio');
INSERT INTO producto (nombre, precio_unitario, tipo) VALUES ('Volkswagen Beetle 1200', 11490, 'Normal');
INSERT INTO producto (nombre, precio_unitario, tipo) VALUES ('Paquete de cartas Magic', 10.99, 'Normal');
INSERT INTO producto (nombre, precio_unitario, tipo) VALUES ('Procesador Intel Core i5-7400', 129.99, 'Normal');
INSERT INTO producto (nombre, precio_unitario, tipo) VALUES ('Disco duro portatil 1 TB ', 39.99, 'Normal');
INSERT INTO producto (nombre, precio_unitario, tipo) VALUES ('Hamburguesa vacuno ', 2.96, 'Frio');
INSERT INTO producto (nombre, precio_unitario, tipo) VALUES ('Tocadiscos', 55.89, 'Normal');
INSERT INTO producto (nombre, precio_unitario, tipo) VALUES ('Disco Back in Black de AC/DC', 21.56, 'Normal');
INSERT INTO producto (nombre, precio_unitario, tipo) VALUES ('Megaman 2', 100, 'Normal');
INSERT INTO producto (nombre, precio_unitario, tipo) VALUES ('Guagua Titsa', 150000,'Normal');
INSERT INTO producto (nombre, precio_unitario, tipo) VALUES ('Mantequilla La Irlandesa', 1.59, 'Frio');
INSERT INTO producto (nombre, precio_unitario, tipo) VALUES ('Jugo Don Simon de Naranja', 1.23, 'Frio');
INSERT INTO producto (nombre, precio_unitario, tipo) VALUES ('Robot Aspirador', 159.89, 'Normal');
INSERT INTO producto (nombre, precio_unitario, tipo) VALUES ('Cepillo de dientes', 1.52, 'Normal');
INSERT INTO producto (nombre, precio_unitario, tipo) VALUES ('Pasta de dientes Colgate', 1.33, 'Normal');
INSERT INTO producto (nombre, precio_unitario, tipo) VALUES ('Muñeca Pinypon', 5.99,  'Normal');
INSERT INTO producto (nombre, precio_unitario, tipo) VALUES ('Palitos de cangrejo', 2.99, 'Congelados');
INSERT INTO producto (nombre, precio_unitario, tipo) VALUES ('Bicicleta de montaña', 250, 'Normal');
INSERT INTO producto (nombre, precio_unitario, tipo) VALUES ('Almohadas viscoelàsticas', 50, 'Normal');
INSERT INTO producto (nombre, precio_unitario, tipo) VALUES ('Figura de Alien tamaño real', 2500, 'Normal');
INSERT INTO producto (nombre, precio_unitario, tipo) VALUES ('E.T la pelicula', 15.99, 'Normal');
INSERT INTO producto (nombre, precio_unitario, tipo) VALUES ('Berlinas', 2, 'Normal');
INSERT INTO producto (nombre, precio_unitario, tipo) VALUES ('Croissant ', 2, 'Normal');
INSERT INTO producto (nombre, precio_unitario, tipo) VALUES ('Botella de vino Dime Que si', 1.99, 'Normal');
INSERT INTO producto (nombre, precio_unitario, tipo) VALUES ('Silla de madera', 57, 'Normal');
INSERT INTO producto (nombre, precio_unitario, tipo) VALUES ('Xiaomi Redmi S2', 150, 'Normal');
INSERT INTO producto (nombre, precio_unitario, tipo) VALUES ('Pendientes Oro Rosa', 12.63, 'Normal');
INSERT INTO producto (nombre, precio_unitario, tipo) VALUES ('Bidon de plastico', 10.99, 'Normal');
INSERT INTO producto (nombre, precio_unitario, tipo) VALUES ('Marco de madera', 5,99,'Normal');
INSERT INTO producto (nombre, precio_unitario, tipo) VALUES ('Hacha larga', 30.50, 'Normal');
INSERT INTO producto (nombre, precio_unitario, tipo) VALUES ('Yogur de coco', 2.13, 'Frio');
INSERT INTO producto (nombre, precio_unitario, tipo) VALUES ('Lomo adobado', 7.99, 'Frio');
INSERT INTO producto (nombre, precio_unitario, tipo) VALUES ('Bombilla', 5.99, 'Normal');
INSERT INTO producto (nombre, precio_unitario, tipo) VALUES ('Pechuga de pollo', 2.99, 'Frio');
INSERT INTO producto (nombre, precio_unitario, tipo) VALUES ('Marihuana terapeutica 2g', 10, 'Normal');
INSERT INTO producto (nombre, precio_unitario, tipo) VALUES ('Macarrones', 1.99, 'Normal');
INSERT INTO producto (nombre, precio_unitario, tipo) VALUES ('Pulpo', 27.99, 'Congelados');
INSERT INTO producto (nombre, precio_unitario, tipo) VALUES ('Chicharro', 6.99, 'Congelados');
INSERT INTO producto (nombre, precio_unitario, tipo) VALUES ('Bolsa de papas bonitas', 10, 'Normal');
INSERT INTO producto (nombre, precio_unitario, tipo) VALUES ('Camisetas FUCK YOU', 7.99, 'Normal');
INSERT INTO producto (nombre, precio_unitario, tipo) VALUES ('Fanta de naranja 33cl', 0.69, 'Frio');
INSERT INTO producto (nombre, precio_unitario, tipo) VALUES ('Chorizo revilla', 1.99, 'frio');
INSERT INTO producto (nombre, precio_unitario, tipo) VALUES ('Balon de futbol', 15.99, 'Normal');
INSERT INTO producto (nombre, precio_unitario, tipo) VALUES ('Bolsa de garbanzos', 1.50, 'Normal');
INSERT INTO producto (nombre, precio_unitario, tipo) VALUES ('Destornillador de punta plana', 2.50, 'Normal');
INSERT INTO producto (nombre, precio_unitario, tipo) VALUES ('Destornillador de punta de estrella', 2.51,'Normal');
INSERT INTO producto (nombre, precio_unitario, tipo) VALUES ('Nintendo 64', 64, 'Normal');
INSERT INTO producto (nombre, precio_unitario, tipo) VALUES ('Super Mario 64', 64, 'Normal');
INSERT INTO producto (nombre, precio_unitario, tipo) VALUES ('Martillo de carpintero', 42.89, 'Normal');
INSERT INTO producto (nombre, precio_unitario, tipo) VALUES ('Cables HDMI de 20m', 39.99, 'Normal');
INSERT INTO producto (nombre, precio_unitario, tipo) VALUES ('Los cazafantasmas', 15.99, 'Normal');
INSERT INTO producto (nombre, precio_unitario, tipo) VALUES ('Patinete electrico', 259.99, 'Normal');
INSERT INTO producto (nombre, precio_unitario, tipo) VALUES ('Botella de te de melocoton', 0.99, 'Frio');
INSERT INTO producto (nombre, precio_unitario, tipo) VALUES ('Bolsas de te marihuana', 2.99, 'Normal');
INSERT INTO producto (nombre, precio_unitario, tipo) VALUES ('Tazas de cafe', 2.99, 'Normal');
INSERT INTO producto (nombre, precio_unitario, tipo) VALUES ('Cesped artificial 40mm2', 3.99, 'Normal');
INSERT INTO producto (nombre, precio_unitario, tipo) VALUES ('Bote de salsa de tomate', 1.99, 'Frio');
INSERT INTO producto (nombre, precio_unitario, tipo) VALUES ('Bote de mojo picon', 2.30, 'Frio');
INSERT INTO producto (nombre, precio_unitario, tipo) VALUES ('Muslos de pollo', 4.99, 'Congelados');
INSERT INTO producto (nombre, precio_unitario, tipo) VALUES ('Bolsa de gueldes', 5.99, 'Congelados');
INSERT INTO producto (nombre, precio_unitario, tipo) VALUES ('Paquete de choco krispies', 3.99, 'Normal');
INSERT INTO producto (nombre, precio_unitario, tipo) VALUES ('Magdalenas', 1.99, 'Normal');
INSERT INTO producto (nombre, precio_unitario, tipo) VALUES ('Paquete de Conguitos', 2.99, 'Normal')