INSERT INTO muelle (id_zona, disponible) VALUES ('A', false);
INSERT INTO muelle (id_zona, disponible) VALUES ('A', true);
INSERT INTO muelle (id_zona, disponible) VALUES ('A', true);
INSERT INTO muelle (id_zona, disponible) VALUES ('B', true);
INSERT INTO muelle (id_zona, disponible) VALUES ('B', false);
INSERT INTO muelle (id_zona, disponible) VALUES ('B', true);
INSERT INTO muelle (id_zona, disponible) VALUES ('C', true);
INSERT INTO muelle (id_zona, disponible) VALUES ('C', false);
INSERT INTO muelle (id_zona, disponible) VALUES ('C', false);
INSERT INTO muelle (id_zona, disponible) VALUES ('D', false);
INSERT INTO muelle (id_zona, disponible) VALUES ('D', false);
INSERT INTO muelle (id_zona, disponible) VALUES ('D', true);
INSERT INTO muelle (id_zona, disponible) VALUES ('E', true);
INSERT INTO muelle (id_zona, disponible) VALUES ('E', true);
INSERT INTO muelle (id_zona, disponible) VALUES ('E', true);
INSERT INTO muelle (id_zona, disponible) VALUES ('F', false);
INSERT INTO muelle (id_zona, disponible) VALUES ('F', true);
INSERT INTO muelle (id_zona, disponible) VALUES ('F', false)